### ISSUE TITLE
Bind to 127.0.0.1

### ISSUE THREAD

**Issue by MartinKavik** [viniciusgerevini/http-test-server#7]
Hi,
is there a way how to force server to listen on `127.0.0.1`?  I see some `localhost` strings hard-coded in the lib's code so I'm not sure.
It works on `localhost` without problems, but it doesn't respond to requests with IP.

Motivation - I use `http-test-server` in benchmarks and there is a big difference between `localhost` and `127.0.0.1` probably because of DNS resolving. 

Win 10  |  http-test-server = "2.0.1"  |  rustc 1.43.1
Thank you for the answer and for the library!

**Comment by viniciusgerevini** [comment]
Hi @MartinKavik . You have a good point, I hadn't really thought about the DNS resolution.
I believe it makes sense to use thr local ip instead of localhost. I'll make some tests and I get back to you soon. Thanks for the suggestion :)

**Comment by viniciusgerevini** [comment]
Hi @MartinKavik ,

When using localhost on Windows, it must be binding the socket to the external interface instead of loopback `127.0.0.1`. This would explain why you can't access it on `127.0.0.1`, and maybe also the performance difference. I'm able to access both ways on linux and MacOS, but you are right about the extra lookup required.

I should have used `127.0.0.1` since the begining, as it doesn't rely on the host file and also doesn't have the risk of leaking the test server through your external IP.

I'll land version 2.1.0 soon, which uses 127.0.0.1 internally. Thanks a lot for pointing out this issue. I hope this solves your problem. :)

**Comment by MartinKavik** [comment]
@viniciusgerevini Thanks, tested and works great. Benchmark results are better. 
I plan to use your library in [Seed](https://github.com/seed-rs/seed), once we need more integration tests :)

**Comment by viniciusgerevini** [comment]
That's awesome. Let me know if you think there is any missing feature.

By the way, Seed looks promising. I wasn't aware of it. :+1: Nice work
